on:
  push:
    branches:
    - '*'
  pull_request:
  workflow_dispatch:

jobs:
  version:
    uses: PurpleBooth/common-pipelines/.github/workflows/commit-check.yml@main

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - version
    outputs:
      version_bump: ${{ steps.release.outputs.version_bump }}
      current_version: ${{ steps.release.outputs.current_version }}
      previous_version: ${{ steps.release.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: PurpleBooth/versio-release-action@v0.1.13
        id: release

  generate-github-release:
    if: needs.release.outputs.version_bump
    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        fetch-depth: 0
        ref: v${{ needs.release.outputs.current_version }}
    - name: Generate a changelog
      uses: PurpleBooth/changelog-action@v0.3.3
      with:
        config: cliff.toml
        args: --verbose v${{ needs.release.outputs.previous_version }}..v${{ needs.release.outputs.current_version }}
        output: CHANGELOG.md
    - id: create_release
      uses: ncipollo/release-action@v1.11.1
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: CHANGELOG.md
        name: Release v${{ needs.release.outputs.current_version }}
        tag: v${{ needs.release.outputs.current_version }}
